### ISSUE TITLE
Update to use the incredible new Readability

### ISSUE THREAD

**Issue by NilsEnevoldsen** [MHordecki/readability-redux#20]
I'm not sure if the new Readability still uses the same architecture, but there is still a bookmarklet available: https://www.readability.com/bookmarklets/

**Comment by MHordecki** [comment]
From what I've read there is an official extension now for that: https://www.readability.com/addons/

**Comment by NilsEnevoldsen** [comment]
I don't know how I missed that. Thanks. Regretfully, I think the advent of that extension means I will no longer be using Readability Redux.

Mr. Hordecki, thanks so much for a wonderful extension. I appreciate it.
