### ISSUE TITLE
Options.js won't load?

### ISSUE THREAD

**Issue by feliven** [MHordecki/readability-redux#3]
I've been having this issue with Readability Redux for a while now. The Readability bookmarklet works just fine, the extension works on both stable and beta versions on Windows XP and Ubuntu 9.10 and 10.04 in virtual machines, but I can't make it work on my main copy of Chrome on Windows 7 anymore!

You can see the bug in this screenshot ( http://imgur.com/4YHCF.png ): the preview pane should have the three buttons on the left and should change according to the options I set above. None of these happen. I'm guessing there's an issue with options.js, since I believe that is the file that renders the three buttons on the left. I don't know, I'm no expert.

I've done everything I could to make this extension work: I've uninstalled and reinstalled it, I've reinstalled Chrome (after cleaning up the registry and rebooting), I've replaced the extension files on the Chrome folder with the files from this repository, I've replaced the files with the ones on the Windows XP virtual machine (since the extension works there)... still, the bug won't go away.

I'm running Chrome 5.0.375.29 beta on Windows 7 Ultimate, but I've had this problem with previous beta versions.

**Comment by MHordecki** [comment]
Interesting! One thing: When in options tab, launch Chrome's javascript console (in the main menu: Developer > JavaScript Console) - are there any errors (in red) written in it? If so, could you copy-paste it here (or pastebin, etc).

**Comment by feliven** [comment]
There you go:

options.js:52  Uncaught TypeError: Cannot call method 'get_settings' of null
options.js:83  Uncaught TypeError: Cannot call method 'create_javascript' of null

If you need anything else, let me know.

**Comment by NilsEnevoldsen** [comment]
I cannot reproduce (Chrome 5.0.375.38 beta, Windows 7). It looks like both errors are because Chrome cannot find Readability Redux's "background page". If you open the Extensions page and turn on Developer mode, do you see a link to "redux/background.html" under Readability Redux?

**Comment by feliven** [comment]
I do! http://prntscr.com/doym

(Chrome 5.0.375.38 beta, W7)

edit: damn it, did I just close this case? It's not been solved yet!
