### ISSUE TITLE
Need newer Readability version

### ISSUE THREAD

**Issue by NilsEnevoldsen** [MHordecki/readability-redux#4]
Readability has been updated to deal with another parsing error on the New York Times.

See http://code.google.com/p/arc90labs-readability/issues/detail?id=477

**Comment by MHordecki** [comment]
Updated in 1.2

**Comment by NilsEnevoldsen** [comment]
Sweet. That, plus a hotkey, plus text fragments, plus the new links-to-footnotes. You rock. Thanks.
