### ISSUE TITLE
Readability redux fails to install on Mac Chrome 5.0.375.127

### ISSUE THREAD

**Issue by oriregev** [MHordecki/readability-redux#6]
I've been using Readability on Firefox for some time and I love it, thanks for a great extension.

I'm trying to install Readability on Google Chrome from the Google Chrome Extensions gallery and the installation fails with the following error:

Extension Install Failure
Invalid value for 'content_scripts[0].matches[0]'.

OS: Mac OS X, Version 10.6.4
Google Chrome Version: 5.0.375.127

Thanks,
Ori

**Comment by sapphirecat** [comment]
Same error for me with: Chromium 5.0.375.125 (53311) Ubuntu 10.04

(And apparently many others, judging by the comments at the Chrome extension page.)

**Comment by oriregev** [comment]
Seems to be installing fine now:

Mac OS X, version 10.6.5
Readability Redux version 1.3 (2010.08.14)
Google Chrome version 7.0.517.44
